### ISSUE TITLE
start does not open here

### ISSUE THREAD

**Issue by sladejr** [dwiza3962/mff_auto#10]
I even tried to open it as an administrator, but it doesn't work.

**Comment by dwiza3962** [comment]
Hi sladejr, 

Once I took this over I really only got it working through building it and running it out of the build directory even that that took some time.

I thought by following the common release process that was setup things would work but something is causing it to not open and was never really able to figure out how to repackage it.

If you have a little bit of development experience, go ahead and download PyCharm and load up this code base in it.    There should be a plugin that works with the requirements.txt file to load in all your dependencies (the IDE should recognize it), then run

.\app_gui.py at the terminal and it should come up like it used to.

If that is too much - I'll try to see what it would take to package things up, but a few things are broken right now with the last few releases.

GBR has issues and some other game modes like WBU menu screens have moved around.   I haven't even begun to look at GBR and the character team selections there.  Now it looks like epic quest might be a little broken.   Code where there needs to do a scrolling window seems pretty tough to get right.

It's hard to get time on this as I really only wanted to get it going to ensure I get my dailies done, but it's taking a bit of time to test and debug all the fixes and changes.

Try to pull down the code and load things up in PyCharm and see if you can get it going.     Note: I'm using a really older version of Nox 6.6.1.5

**Comment by dwiza3962** [comment]
Guys I mucked with the requirements file because I wasn't aware that was generally bad.   I just pushed up a new release 0.15.0 let me know if this one actually runs.     I'll hope to have some more updates in a few days.

**Comment by sladejr** [comment]
does the bot work better on nox 6.6.1.5 than on 7.0.1.0?

**Comment by dwiza3962** [comment]
I couldn't ever get things working right on any version of 7.X.      I had all kinds of google play services issues on most NOX versions.     I was able to get around it by disabling some location services on NOX 6.6.1.5.     I say if you have 7.x working fine - then keep at it since it's the later version.     One thing I noticed on sluggish machines, you really have to tinker with your graphics.    When I was on my old computer - I had to be on 1600x900 and tune graphics down real low.     Even now I'm hitting the occasional application crash, but I don't think it has anything to do with the bot just my subpar machine.

Right now, I have a laptop with onboard graphics (AMD) but I'm driving quite a few monitors.   I have to run graphics to medium and framerate to low to get it to work the best for me.

**Comment by sladejr** [comment]
I'm using 7.0.1.0, but sometimes some missions just give the bot an error and it's complete, giant boss sometimes crashes on the exit confirm screen, do you have these problems in 6.6.1.5?

**Comment by dwiza3962** [comment]
I'm on 6.6.1.5, but I've been having these same problems too, but it only started appearing once I fixed the dependency problem to deliver a release build that runs.   I'm trying to understand if it's a result in one of the dependent packages that was updated, then rolled back and which one it could be.    I'm relatively new to this whole python package system with requirements.txt files, and even how / where to troubleshoot it.   So bear with me.   I can reach out to @tmarenko to see if he has any ideas.    The good news is I'm having the same problem so it's reproduceable, but the bad news seems to be the sporadic nature of the app crashing and if its related to nox in general, the graphics settings of nox and application, or a dependency, so it could be a little bit to track down.

**Comment by sladejr** [comment]
I don't know python so I can't move it now, but I can try to study and learn to try to help you, it would be great if tmarenko could help you.

**Comment by sladejr** [comment]
I forgot to warn you, the shadowland beginner roster is not working, only strong and maximum

**Comment by dwiza3962** [comment]
was the last release working better for you, I know it wasn't out very long - 0.15.0?

**Comment by dwiza3962** [comment]
I rolled back requirements file to the version on 0.15.0 and today has seemed more stable.    Got through the whole queue without crashing.

**Comment by tmarenko** [comment]
I can confirm that upgrading packages could lead to recognition problems. If you really not sure what upgraded package do and you don't need "new features" from it - stay on the same version.

**Comment by sladejr** [comment]
> 



> I rolled back requirements file to the version on 0.15.0 and today has seemed more stable. Got through the whole queue without crashing.

how do i get back to 0.15?

**Comment by sladejr** [comment]
> I can confirm that upgrading packages could lead to recognition problems. If you really not sure what upgraded package do and you don't need "new features" from it - stay on the same version.

@tmarenko  I have 2 accounts, would you go back to playing and developing the bot if I give you one?

**Comment by tmarenko** [comment]
@sladejr I'm sorry but it's not about having another account (because I had 2-3 for testing purposes). I'm just devasted that all my time and money were wasted so I moved on from this game.

**Comment by sladejr** [comment]
> @sladejr Desculpe, mas não se trata de ter outra conta (porque eu tinha 2-3 para fins de teste). Estou devastado que todo o meu tempo e dinheiro foram desperdiçados, então deixei este jogo.

my other account is good it has 26 t3 and 9 exceeded, if you want to go back i can give it to you

**Comment by sladejr** [comment]
> @sladejr Desculpe, mas não se trata de ter outra conta (porque eu tinha 2-3 para fins de teste). Estou devastado que todo o meu tempo e dinheiro foram desperdiçados, então deixei este jogo.

I even got banned from my main account as I invested a lot and until today they didn't even want to reveal the reason and I was pretty devastated too
