### ISSUE TITLE
i need a queue list

### ISSUE THREAD

**Issue by sladejr** [dwiza3962/mff_auto#25]
Could you send me your queue list so I know what to put?

**Comment by dwiza3962** [comment]
Sure - 

This is the one I primarily use while I'm testing.

`[
   [
      {
         "mode_name": "DISPATCH MISSION: ACQUIRE ALL REWARDS",
         "checked": false,
         "action": true
      },
      {
         "mode_name": "FRIENDS: SEND ALL TOKENS",
         "checked": false,
         "action": true
      },
      {
         "mode_name": "FRIENDS: ACQUIRE ALL TOKENS",
         "checked": false,
         "action": true
      },
      {
         "mode_name": "ENERGY: COLLECT FREE 24H",
         "checked": false,
         "action": true
      },
      {
         "mode_name": "ENERGY: COLLECT VIA ASSEMBLE POINTS",
         "checked": false,
         "use_all_points": true,
         "action": true
      },
      {
         "mode_name": "ALLIANCE: CHECK-IN",
         "checked": false,
         "action": true
      },
      {
         "mode_name": "ALLIANCE: DONATE",
         "checked": false,
         "donate_gold": true,
         "donate_memento": true,
         "action": true
      },
      {
         "mode_name": "ALLIANCE: BUY ITEMS FROM STORE",
         "checked": false,
         "items": [
            "ALLIANCE_STORE_ENERGY_ITEM_1",
            "ALLIANCE_STORE_BOOST_POINT_ITEM_4",
            "ALLIANCE_STORE_HIDDEN_TICKET_ITEM_3",
            "ALLIANCE_STORE_UNIFORM_EXP_CHIP_ITEM_2"
         ],
         "buy_all_available": true,
         "action": true
      },
      {
         "mode_name": "ALLIANCE: REQUEST SUPPORT",
         "checked": false,
         "support_item": "ALLIANCE_SUPPORT_REQUEST_BLACK_ANTI_MATTER",
         "action": true
      },
      {
         "mode_name": "ALLIANCE: COLLECT ENERGY FROM CHALLENGES",
         "checked": false,
         "collect_daily": true,
         "collect_weekly": true,
         "action": true
      },
      {
         "mode_name": "DAILY TRIVIA",
         "checked": false,
         "action": true
      },
      {
         "mode_name": "SUPPORT SHOP: BUY MATERIALS",
         "checked": false,
         "materials_list": [
            "SUPPORT_SHOP_MATERIAL_MKRAAN_SHARD",
            "SUPPORT_SHOP_MATERIAL_GEAR_UP_KIT",
            "SUPPORT_SHOP_MATERIAL_UNIFORM_UPGRADE_KIT"
         ],
         "action": true
      },
      {
         "mode_name": "STORE: ACQUIRE FREE HERO CHEST",
         "checked": false,
         "action": true
      },
      {
         "mode_name": "STORE: ACQUIRE FREE ARTIFACT CHEST",
         "checked": false,
         "action": true
      },
      {
         "mode_name": "LEGENDARY BATTLE",
         "checked": false,
         "all_stages": true,
         "times": 1,
         "mode": "NORMAL",
         "battle": "THOR_RAGNAROK",
         "stage": "LB_BATTLE_STAGE_1"
      },
      {
         "mode_name": "TRUE EVOLUTION",
         "checked": false,
         "all_stages": true,
         "times": 1,
         "farm_shifter_bios": false
      },
      {
         "mode_name": "VEILED SECRET",
         "checked": false,
         "all_stages": true,
         "times": 1
      },
      {
         "mode_name": "MUTUAL ENEMY",
         "checked": false,
         "all_stages": true,
         "times": 1,
         "farm_shifter_bios": false
      },
      {
         "mode_name": "THE BIG TWIN",
         "checked": false,
         "all_stages": true,
         "times": 1
      },
      {
         "mode_name": "BEGINNING OF THE CHAOS",
         "checked": false,
         "all_stages": true,
         "times": 1,
         "farm_shifter_bios": false
      },
      {
         "mode_name": "DOOM'S DAY",
         "checked": false,
         "all_stages": true,
         "times": 1,
         "farm_shifter_bios": false
      },
      {
         "mode_name": "FATE OF THE UNIVERSE",
         "checked": false,
         "all_stages": true,
         "times": 1,
         "farm_shifter_bios": false
      },
      {
         "mode_name": "PLAYING HERO",
         "checked": false,
         "all_stages": true,
         "times": 1,
         "farm_shifter_bios": false
      },
      {
         "mode_name": "HEROES REUNITED",
         "checked": false,
         "all_stages": true,
         "times": 1
      },
      {
         "mode_name": "ALLIANCE BATTLE",
         "checked": false,
         "mode": "ALL_BATTLES"
      },
      {
         "mode_name": "SQUAD BATTLE",
         "checked": false,
         "mode": "DAILY_RANDOM"
      },
      {
         "mode_name": "CO-OP PLAY",
         "checked": true,
         "all_stages": true,
         "times": 1
      },
      {
         "mode_name": "TIMELINE BATTLE",
         "checked": true,
         "all_stages": true,
         "times": 1,
         "skip_opponent_count": 0
      },
      {
         "mode_name": "INBOX - CHESTS: ACQUIRE ALL",
         "checked": true,
         "action": true
      },
      {
         "mode_name": "INBOX - GIFTS: ACQUIRE ALL",
         "checked": true,
         "acquire_energy": true,
         "action": true
      },
      {
         "mode_name": "DAILY REWARDS: ACQUIRE ALL",
         "checked": true,
         "action": true
      },
      {
         "mode_name": "WEEKLY REWARDS: ACQUIRE ALL",
         "checked": true,
         "action": true
      }
   ],
   [
      {
         "mode_name": "ISO-8: UPGRADE",
         "checked": true,
         "times_for_each_upgrade": 99,
         "iso_to_upgrade": [
            "ISO8_CHAOTIC_TAB"
         ],
         "iso_to_use": [
            "ISO8_POWERFUL_ENHANCE",
            "ISO8_AMPLIFYING_ENHANCE",
            "ISO8_IMPREGNABLE_ENHANCE",
            "ISO8_ABSORBING_ENHANCE",
            "ISO8_VITAL_ENHANCE",
            "ISO8_FIERCE_ENHANCE",
            "ISO8_NIMBLE_ENHANCE",
            "ISO8_CHAOTIC_ENHANCE"
         ],
         "stars_to_use": [
            "ISO8_ENHANCE_1_STAR",
            "ISO8_ENHANCE_2_STAR",
            "ISO8_ENHANCE_3_STAR",
            "ISO8_ENHANCE_4_STAR"
         ],
         "action": true
      },
      {
         "mode_name": "ISO-8: LOCK",
         "checked": true,
         "iso_to_lock": [
            "ISO8_CHAOTIC_TAB"
         ],
         "options_to_lock": [
            "(ALL BASIC ATTACKS INCREASE){e<=3}.*\\n(HP).*",
            "(PHYSICAL ATTACK){e<=3}.*\\n(HP).*",
            "(ENERGY ATTACK){e<=3}.*\\n(HP).*"
         ],
         "action": true
      },
      {
         "mode_name": "ISO-8: UPGRADE",
         "checked": true,
         "times_for_each_upgrade": 99,
         "iso_to_upgrade": [
            "ISO8_CHAOTIC_TAB"
         ],
         "iso_to_use": [
            "ISO8_POWERFUL_ENHANCE",
            "ISO8_AMPLIFYING_ENHANCE",
            "ISO8_IMPREGNABLE_ENHANCE",
            "ISO8_ABSORBING_ENHANCE",
            "ISO8_VITAL_ENHANCE",
            "ISO8_FIERCE_ENHANCE",
            "ISO8_NIMBLE_ENHANCE"
         ],
         "stars_to_use": [
            "ISO8_ENHANCE_1_STAR",
            "ISO8_ENHANCE_2_STAR",
            "ISO8_ENHANCE_3_STAR",
            "ISO8_ENHANCE_4_STAR",
            "ISO8_ENHANCE_5_STAR"
         ],
         "action": true
      },
      {
         "mode_name": "ISO-8: COMBINE",
         "checked": true,
         "times_for_each_combine": 99,
         "iso_to_combine": [
            "ISO8_CHAOTIC_TAB"
         ],
         "action": true
      },
      {
         "mode_name": "COMIC CARDS: UPGRADE ALL",
         "checked": true,
         "action": true
      },
      {
         "mode_name": "CUSTOM GEAR: UPGRADE",
         "checked": true,
         "times": 99,
         "action": true
      },
      {
         "mode_name": "ARTIFACT: DISMANTLE",
         "checked": true,
         "artifact_stars": [
            "ARTIFACT_DISMANTLE_STAR_1",
            "ARTIFACT_DISMANTLE_STAR_2"
         ],
         "action": true
      }
   ],
   [
      {
         "mode_name": "RESET TODAY'S WORLD BOSS",
         "checked": false,
         "max_resets": 99,
         "world_boss": [
            "Proxima Midnight",
            "Black Dwarf",
            "Corvus Glave",
            "Supergiant"
         ],
         "action": true
      },
      {
         "mode_name": "WORLD BOSS",
         "checked": false,
         "all_stages": true,
         "times": 1,
         "mode": "ULTIMATE",
         "boss": "TODAYS_BOSS",
         "difficulty": 20,
         "sync_character_and_ally_teams": false
      },
      {
         "mode_name": "ALLIANCE BATTLE",
         "checked": false,
         "mode": "ALL_BATTLES"
      },
      {
         "mode_name": "CO-OP PLAY",
         "checked": false,
         "all_stages": true,
         "times": 1
      },
      {
         "mode_name": "SHADOWLAND",
         "checked": false,
         "times": 35,
         "roster_mode": "MAXIMUM_ROSTER"
      }
   ],
   [
      {
         "mode_name": "WORLD EVENT",
         "checked": false,
         "event": true
      },
      {
         "mode_name": "EVENT WORLD BOSS",
         "checked": false,
         "sync_character_and_ally_teams": false,
         "event": true
      },
      {
         "mode_name": "SQUAD BATTLE",
         "checked": true,
         "mode": "ALL_BATTLES"
      }
   ]
]`
