### ISSUE TITLE
Can't open the application

### ISSUE THREAD

**Issue by Zennehad** [dwiza3962/mff_auto#8]
Hello and thanks for continuing with the project!

I would like to report that I am trying a clean install with your version, however the setup opens and closes immediately, without opening the application GUI.

Could you verify?

**Comment by sladejr** [comment]
did you manage to solve it?

**Comment by Zennehad** [comment]
Nope

**Comment by dwiza3962** [comment]
Sorry all - It's missing some dependency.    @Zennehad see my post here.  https://github.com/dwiza3962/mff_auto/issues/10.    I'll see if I can figure out what the dependency issue is or it's complaining about.      Did you all use this before it was archived?

**Comment by dwiza3962** [comment]
it's complaining about Traceback (most recent call last):
  File "app_gui.py", line 5, in <module>
    from PyQt5 import QtCore, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

So it's pretty much stuck in python requirements hell when building the dependencies - working through it.

**Comment by dwiza3962** [comment]
Guys I mucked with the requirements file because I wasn't aware that was generally bad.   I just pushed up a new release 0.15.0 let me know if this one actually runs.     I'll hope to have some more updates in a few days.

**Comment by Zennehad** [comment]
Its working like a charm! Thanks a lot!

**Comment by sladejr** [comment]
> Está funcionando como um encanto! Muito obrigado!

what version of nox are you using?
